# Generated by Django 3.0.8 on 2020-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('product', models.TextField(blank=True, max_length=5000, null=True)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
