# Generated by Django 3.1.4 on 2021-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogclass',
            name='video',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blogclass',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
