# Generated by Django 3.1.4 on 2021-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogclass',
            name='imageW',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogclass',
            name='imaheH',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogclass',
            name='ARdescription',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='blogclass',
            name='ENdescription',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='blogclass',
            name='FRdescription',
            field=models.TextField(max_length=2000),
        ),
    ]
