# Generated by Django 3.1.4 on 2021-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210510_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogclass',
            name='image',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='pics'),
        ),
    ]
