# Generated by Django 3.1.4 on 2021-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisanalProd', '0003_auto_20210114_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanalprod',
            name='ARdescription',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='artisanalprod',
            name='ENdescription',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='artisanalprod',
            name='FRdescription',
            field=models.TextField(max_length=2000),
        ),
    ]
