# Generated by Django 3.0 on 2021-01-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisanalProd', '0004_auto_20210116_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanalprod',
            name='ARdescription',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='artisanalprod',
            name='ENdescription',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='artisanalprod',
            name='FRdescription',
            field=models.TextField(max_length=2000),
        ),
    ]
