# Generated by Django 3.1.2 on 2020-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENtitle', models.CharField(max_length=200)),
                ('FRtitle', models.CharField(max_length=200)),
                ('ARtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('ENdescription', models.TextField(max_length=1200)),
                ('FRdescription', models.TextField(max_length=1200)),
                ('ARdescription', models.TextField(max_length=1200)),
                ('price', models.FloatField(max_length=1000)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
