# Generated by Django 3.1.4 on 2021-01-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalProd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalprod',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
