# Generated by Django 3.1.2 on 2020-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('princ', '0002_auto_20200913_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('aProduct', models.ManyToManyField(blank=True, to='princ.ArtisanalProduct')),
                ('nProduct', models.ManyToManyField(blank=True, to='princ.NaturalProduct')),
            ],
        ),
    ]
